version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:django
    container_name: mega_market_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: postgres_db
    healthcheck:
      test: pg_isready -U ${DATABASE_USER}
      interval: 5s
      retries: 5
